version: '3.6'

services:
  back:
    build:
      context: .
    volumes:
      - .:/projeto
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - HOST_NAME=db
      - TEMPLATES_AUTO_RELOAD=True
      - PYTHONUNBUFFERED=1
      - APPLY_TO_ALL=True
    ports:
      - 5000:5000

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017

  web:
    build: ./app
    ports:
      - 3000:3000